required_columns:
  - subject
  - body
  - type

expected_columns:
  - subject
  - body
  - answer
  - type
  - queue
  - priority
  - language
  - version
  - tag_1
  - tag_2
  - tag_3
  - tag_4
  - tag_5
  - tag_6
  - tag_7
  - tag_8

checks:
  allow_nulls:
    subject: false
    body: false
    type: false
  
  allow_duplicates: true